name: Auto Kalender Puasa & Sholat

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create credentials.json
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

      - name: Create token.json
        run: echo '${{ secrets.TOKEN_JSON }}' > token.json

      - name: Run script (Puasa)
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python script.py

      - name: Run script (Sholat)
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        run: python script_sholat.py

      - name: Commit log.txt
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add -f log.txt
          git commit -m "update log" || echo "no change"
          git push
